baseurl = "https://pso2.lei202.com/"  # Include trailing slash
title = "Leies PSO2Diary"
theme = "hugo-swift-theme"
# theme = "swift"
author = "レイエス(lei202)"
copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."
canonifyurls = true
paginate = 4
hasCJKLanguage = true
# Enable syntax highlighting
# comment on delete the following lines 11 ~ 13
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
disqusShortname = "pso2diary"

[params]
  [params.designer]
    name = "Weru"
    url = "https://www.linkedin.com/in/dan-weru-profile/"
  [[params.authors]]
    name = "レイエス" # can be nickname # if fullName 👇🏻 isn't set, name will be displayed on author card
    fullName = "レイエス(lei202)" # optional. If set, it will display on author card
    bio = "そこら辺に居るサモナーアークス"
    photo = "myPhotoFile.jpg"
    url = "https://me.lei202.com/"
  # ga_analytics = "" # google analytics ID e.g UA-116386578-1

  # ga_verify = "" # google verification code e.g 5jb-rxeBfITeJQKOuUss3ud6FPGTxXkCho-ZN5qlrZg
  twitter = "@Leies_pso" # twitter handle e.g @weru
  # logo = "logo.png"
  author = "レイエス" # default author
  # image = "placeholder-image.png" # used whenever a page image is not set
  # blogDir = "blogFolderName" # uncomment and edit to exclude normal pages ... see issue #57
# [params.staticman]
#   endpoint = ""  # URL of your own API deployment (without trailing slash), default: "https://staticman-frama.herokuapp.com"
#   gitProvider = "github"  # Either "github" or "gitlab"
#   username = "username"  # GitHub/GitLab user name
#   repository = "repo"  # GitHub/GitLab user name
#   branch = "master"  # Branch holding the source code for your site, should match the `branch` parameter in `staticman.yml`
#
#   # If you use reCAPTCHA v2, you must also set these parameters in staticman.yml
#   [Params.staticman.reCaptcha]
#     siteKey = ""  # Use your own site key, you need to apply for one on Google
#     secret  = ""  # ENCRYPT your password by going to https://<staticman-endpoint>/v3/encrypt/<your-site-secret>

[markup]
  [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true # change to true to enable inclusion of rawHTML and math functions
    xhtml = false

[menu]
  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 2
  [[menu.main]]
    name = "アラキナ(メインキャラ)"
    url = "tags/アラキナ/"
    weight = 3
  [[menu.main]]
    name = "英治"
    url = "tags/英治/"
    weight = 4
  [[menu.main]]
    name = "ss"
    url = "tags/ss/"
    weight = 5
